sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t cbethin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cbethin/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-587088104673"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY