sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t cbethin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cbethin/docker-react npm run test

